### PR TITLE
Build using latest sencha / ExtJS during CI

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests to upgrade to using ext 6.2.0 and the newest sencha cmd (v6.2.1.29).

Please review.

### CODE REVIEW

**Comment by marcjansen** [comment]
I have no idea why the build fails here… investigating now

**Comment by marcjansen** [comment]
Since the build is green now, I think this is ready to be reviewed. This is basically the same we had for GeoExt: https://github.com/geoext/geoext3/pull/193

**Comment by annarieger** [comment]
Looks very good to me, @marcjansen! Thanks for upgrading :+1

**Comment by marcjansen** [comment]
Thanks for the review!

**Pull request merged**
