### PR TITLE
Enhances the reusablity of the CoordinateTransform form.

### PR DESCRIPTION
**Pull request by KaiVolland**
This enhances the reusablity of the CoordinateTransform form.

@reviewers plz test with a currently running project to ensure compatibility.

### CODE REVIEW

**Comment by weskamm** [comment]
Tested in production application, still working fine. The layout needs application-side adjustments (needs more width and height now), but this can be easily adopted. Good to go! :+1:

**Comment by marcjansen** [comment]
I like it as well :+1: 

I'd prefer to rebase this one on top of #68… Do you people agree? ISTM that this one will be easier to update that #68.

**Comment by weskamm** [comment]
i think the same

**Comment by KaiVolland** [comment]
Rebased it as #68 is merged.

**Comment by marcjansen** [comment]
Rebasing left a duplicate key `bind` in the `src/view/form/CoordinateTransform.js` file which in turn correctly made the CI bark. I'll open up another PR with a fix which will replace this one.

**Comment by marcjansen** [comment]
Superseeded by #76.

**Pull request closed without merging**
