### PR TITLE
added new methods do do animation on a layer instead of feature. Fixe…

### PR DESCRIPTION
**Pull request by Unraveler**
Adds new methods to Animation component:
- `doAnimation(feature, animate)`
- 'endAnimation(feature, listenerKey)`

They do an animation on a layer instead of a feature, which was causing error when doing the animation

Also fixes Measure.js, where coordinates were incorrectrly passed to Polygon, whereas geometry should be given instead.

Please review @terrestris/devs

### CODE REVIEW

**Comment by weskamm** [comment]
Changes looking good to me, but the examples are broken now. Please fix them.

**Comment by buehner** [comment]
yes. changes also look good to me. i could already test them in a project. as @weskamm mentioned, the tests seem to be broken

**Comment by weskamm** [comment]
> yes. changes look good to me, too. i could successfully test them in a project. as @weskamm mentioned, the tests seem to be broken

The fancy examples are broken, not the tests :-)

**Comment by Unraveler** [comment]
Animation and i18n examples are fixed. The update to oOL6.5.0 was missing on the HTML. You can check again @weskamm , @buehner

**Comment by weskamm** [comment]
Looking great again, thanks!

**Pull request merged**
