### PR TITLE
Minor query bugfix.

### PR DESCRIPTION
**Pull request by KaiVolland**

### CODE REVIEW

**Comment by marcjansen** [comment]
These can already be configured by specifying a `legendLayerFilter` in an application override.

**Comment by KaiVolland** [comment]
You are right. I didn't thought on that one. And then didn't thought i can use it in my project. Now i do. So i removed the stuff you mentioned and transformed this to a tiny PR. :)

**Comment by marcjansen** [comment]
Now that is cool! Thanks for reconsidering.

**Comment by marcjansen** [comment]
Please merge

**Pull request merged**
