### PR TITLE
Several enhancements for WMS GetCapabilities form

### PR DESCRIPTION
**Pull request by marcjansen**
This includes:

* a configuration option to also show checkboxes for sublayers
* configurable check/uncheck all layers checkboxes buttons
* configurabl initial state of a layer checkbox
* loadmask while fetching data, parsing it and creating the new UI
* automagically configuring UI disabled state (interactions with
  the list of layers)
* some display of layers in two columns
* scrollable layers-list
* internal restructuring (named functions instead of anonymous ones)
* some inline TODO comments for future tasks

Please review.

### CODE REVIEW

**Comment by buehner** [comment]
:+1: from me

:shipit::neckbeard::bowtie::clap:

**Comment by marcjansen** [comment]
Cheers for the review!

**Comment by buehner** [comment]
:see_no_evil::hear_no_evil::speak_no_evil:

**Comment by marcjansen** [comment]
Trust me, it'll all turn out good…

**Pull request merged**
