### PR TITLE
Added CSRF header util

### PR DESCRIPTION
**Pull request by weskamm**
Will get more and more usable in the future when SHOGun2 gets spread..

### CODE REVIEW

**Comment by buehner** [comment]
:+1:

**Comment by marcjansen** [comment]
A nice addition. Some minor remarks:

* The names shoud be configurable and default to the SHOGun2 values.
* The class doesn't have the GPL-header
* and the returns aren't documented.

Please merge once these are adressed.

**Comment by marcjansen** [comment]
You are too fast, guys.

**Comment by weskamm** [comment]
thanks @marcjansen, PR #45 adresses the mentioned issues.
The names you are talking about are the defaults given by spring security, so i kept them as is.

**Pull request merged**
