### PR TITLE
Reenable the autogeneration of API docs

### PR DESCRIPTION
**Pull request by marcjansen**
Title says it all. This is an attempt to reenable the autogeneration of the API docs. It's structurally the same as GeoExt3 has it… but we can only see if it works if we merge this.

Please review.

### CODE REVIEW

**Comment by marcjansen** [comment]
Ping @terrestris/owners, anyone up for a review?

**Comment by annarieger** [comment]
Let's merge and surprise :wink:

**Comment by marcjansen** [comment]
fingers-crossed!

**Comment by marcjansen** [comment]
Seems to have worked as expected https://github.com/terrestris/BasiGX/commit/fd136958518b2779a4a89fe6b99c2ee4c7cbe4a9

**Pull request merged**
