### PR TITLE
[WIP] Fixing the build again

### PR DESCRIPTION
**Pull request by weskamm**
We have the tests failing on travis, but not locally. Trying to fix it with this PR

### CODE REVIEW

**Comment by dnlkoch** [comment]
@weskamm The build is failing.

**Comment by weskamm** [comment]
Funny conclusion:
Loading GeoExt via https://geoext.github.io/geoext3/master/GeoExt.js in script tag of the tests index.html does not work on travis. Including the source code from that URL int eh body of the index.html works.

The problem may resolve itself as it seems to be a connectivity issue. So this PR will stay on standby

**Comment by dnlkoch** [comment]
This still seems to be an issue with the tests on travis, so I suggest to merge this one.

**Comment by marcjansen** [comment]
Can we please cleanup the commit history before merging this?

**Pull request merged**
