### PR TITLE
Change nominatim service to nominatim.terrestris.de

### PR DESCRIPTION
**Pull request by hblitza**
Due to CORS issues with nominatim.openstreetmap.org.

- [x] fix icon issue

### CODE REVIEW

**Comment by hwbllmnn** [comment]
The icon issue is not an issue with the code, https://nominatim.terrestris.de simply does not return icons.

**Comment by marcjansen** [comment]
Can this be merged then? Or is there sth. to be done server side first?

**Comment by hwbllmnn** [comment]
I think we first should see to it that the service returns the icon URLs properly, lest we forget it.

**Comment by hwbllmnn** [comment]
This is ready for review & merge now, turns out the server is running fine but delivering paths instead of URLs.

**Comment by weskamm** [comment]
I like, travis not!

**Comment by hwbllmnn** [comment]
Travis is fixed, merging now

**Pull request merged**
