### PR TITLE
Fixed randomly failing tests

### PR DESCRIPTION
**Pull request by hwbllmnn**
@terrestris/devs please review

### CODE REVIEW

**Comment by marcjansen** [comment]
I am `+0`, e.g. not blocking this.

Personally I would have tried another approach; instead of no longer cleaning up behind (some) individual tests, I would have searched where something isn't properly cleaned up right now. I assume the random test failures stem from not properly cleaning up. But again, I might miss something or misunderstand this. I would love to have another opinion on this.

**Comment by weskamm** [comment]
I see other tests failing on my local machine, we should wait with merging and analyse this in more detail

**Comment by hwbllmnn** [comment]
As far as I could tell, the tests failed _because_ of the cleaning up. I'm not sure why, but I imagine it being a result of either ExtJS failing to properly do so (.destroy), as @weskamm suggested, or PhantomJS doing garbage collection at inconvenient times, or even a combination of both.

Anyway, please note that I only have anecdotal evidence of this fixing the problem (I ran the tests locally ~50 times with none failing). If that's you restarting travis all the time currently, please keep clicking, the issue happens on slow machines much more often than on fast ones :-)

**Comment by weskamm** [comment]
Yes its me restarting travis ;-) But now its time for fireevening

**Comment by hwbllmnn** [comment]
@weskamm agreed, I can very well imagine that other tests may be involved. I'll prepare a longer run right now.

**Comment by hwbllmnn** [comment]
Have a good one ;-)

**Comment by hwbllmnn** [comment]
I pushed another few fixes, that should fix the remaining ones. I just ran 1000 test runs without any failures.

**Comment by weskamm** [comment]
Ok, will merge this now. If the problem occurs again, we should have a deeper look in `setupTestObjects` and `teardownTestObjects` of the `TestUtil`. I had some success temporarily disable the Redlining test, but i think the problem may be found somewhere in updates of phantomjs and asynchronous behaviour of some cleanup /garbage collection things...

**Pull request merged**
